/* Generated by scripts/build-sw.mjs — do not edit by hand (npm run build). */
/* eslint-disable */
const VERSION = 'c10494c41ff6';
const CACHE = 'chorraha-' + VERSION;
const PRECACHE = [
  "./",
  "./assets/fonts/roboto-v51-latin-500.woff2",
  "./assets/fonts/roboto-v51-latin-700.woff2",
  "./assets/fonts/roboto-v51-latin-900.woff2",
  "./assets/fonts/roboto-v51-latin-regular.woff2",
  "./assets/icons/apple-touch-icon.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon.svg",
  "./dist/content/achievements.js",
  "./dist/content/campaign.data.js",
  "./dist/content/campaign.js",
  "./dist/content/daily.js",
  "./dist/content/endless.js",
  "./dist/content/garage.js",
  "./dist/content/generator.js",
  "./dist/content/handmade.js",
  "./dist/content/practice.js",
  "./dist/content/rulesText.js",
  "./dist/core/bot.js",
  "./dist/core/controller.js",
  "./dist/core/dir.js",
  "./dist/core/engine.js",
  "./dist/core/index.js",
  "./dist/core/junction.js",
  "./dist/core/kinematics.js",
  "./dist/core/level.js",
  "./dist/core/path.js",
  "./dist/core/replay.js",
  "./dist/core/rules.js",
  "./dist/core/scoring.js",
  "./dist/core/signals.js",
  "./dist/core/types.js",
  "./dist/core/vehicles.js",
  "./dist/web/app.js",
  "./dist/web/audio.js",
  "./dist/web/dom.js",
  "./dist/web/editor-model.js",
  "./dist/web/fx.js",
  "./dist/web/icons.js",
  "./dist/web/main.js",
  "./dist/web/net/supabase.js",
  "./dist/web/net/sync.js",
  "./dist/web/pwa.js",
  "./dist/web/render/camera.js",
  "./dist/web/render/color.js",
  "./dist/web/render/effects.js",
  "./dist/web/render/looks.js",
  "./dist/web/render/props.js",
  "./dist/web/render/renderer.js",
  "./dist/web/render/scene.js",
  "./dist/web/render/vehicles.js",
  "./dist/web/router.js",
  "./dist/web/save.js",
  "./dist/web/screens/achievements.js",
  "./dist/web/screens/editor.js",
  "./dist/web/screens/garage.js",
  "./dist/web/screens/levels.js",
  "./dist/web/screens/menu.js",
  "./dist/web/screens/play.js",
  "./dist/web/screens/rules.js",
  "./dist/web/screens/settings.js",
  "./dist/web/screens/stats.js",
  "./dist/web/share.js",
  "./dist/web/store.js",
  "./index.html",
  "./manifest.webmanifest",
  "./styles.css"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('chorraha-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // cloud sync (Supabase) and anything else cross-origin always goes to the network
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // the page: network first (fresh deploys), the cached shell when offline
    event.respondWith(
      fetch(req).catch(() => caches.match('./index.html').then((hit) => hit || caches.match('./'))),
    );
    return;
  }
  // game files: cache first — one consistent version per worker
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
