#!/usr/bin/env node
/**
 * Generates sw.js — the offline service worker. It precaches everything the
 * game needs (page, styles, compiled modules, fonts, small icons); the cache
 * name is a hash of all those files, so every change to the build yields a new
 * worker that the browser installs in the background and activates on the
 * next load. Deterministic: same files → byte-identical sw.js (CI checks that
 * the committed sw.js is up to date). Runs as part of `npm run build`.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOP = ['index.html', 'styles.css', 'manifest.webmanifest'];
const DIRS = ['dist', 'assets'];
/** Big install-time icons are fetched by the browser when installing (online) — not precached. */
const SKIP = [/\.map$/, /\.d\.ts$/, /-512\.png$/, /(^|\/)\.[^/]+$/];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

const files = [...TOP.map((f) => join(ROOT, f)), ...DIRS.flatMap((d) => walk(join(ROOT, d)))]
  .map((p) => relative(ROOT, p).split(sep).join('/'))
  .filter((p) => !SKIP.some((re) => re.test(p)))
  .sort();

const hash = createHash('sha256');
for (const f of files) {
  hash.update(f);
  hash.update('\0');
  hash.update(readFileSync(join(ROOT, f)));
  hash.update('\0');
}
const version = hash.digest('hex').slice(0, 12);
const precache = ['./', ...files.map((f) => `./${f}`)];

const sw = `/* Generated by scripts/build-sw.mjs — do not edit by hand (npm run build). */
/* eslint-disable */
const VERSION = '${version}';
const CACHE = 'chorraha-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('chorraha-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // cloud sync (Supabase) and anything else cross-origin always goes to the network
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // the page: network first (fresh deploys), the cached shell when offline
    event.respondWith(
      fetch(req).catch(() => caches.match('./index.html').then((hit) => hit || caches.match('./'))),
    );
    return;
  }
  // game files: cache first — one consistent version per worker
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;

writeFileSync(join(ROOT, 'sw.js'), sw);
console.log(`sw.js: ${precache.length} files, version ${version}`);
