#!/usr/bin/env node
/**
 * Copies the compiled game core + campaign into supabase/functions/_shared/chorraha
 * so the edge function re-simulates replays with EXACTLY the client's engine.
 *   npm run build:edge
 */
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'supabase/functions/_shared/chorraha');
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
for (const dir of ['core', 'content']) {
  cpSync(resolve(root, 'dist', dir), resolve(out, dir), {
    recursive: true,
    filter: (src) => !src.endsWith('.map'),
  });
}
writeFileSync(resolve(out, 'README.md'), 'Generated by `npm run build:edge` from dist/. Do not edit.\n');
console.log(`edge bundle → ${out}`);
